{{- if not .Values.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "smokejumper.serviceAccountName" . }}
  labels:
    {{- include "smokejumper.labels" . | nindent 4 }}
{{- end }}
